server:
  port: ${PORT:8085}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:https://fuzzy-broccoli-wp475v45r5j394p7-8085.app.github.dev}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: API-AI
  r2dbc:
    url: r2dbc:postgresql://NeonDB_owner:npg_z3LUOmRcrI5G@ep-odd-grass-a5zs4hqj-pooler.us-east-2.aws.neon.tech/NeonDB?sslmode=require&channel_binding=require
    username: NeonDB_owner
    password: npg_z3LUOmRcrI5G

rapidapi:
  youtube-mp36:
    url: https://youtube-mp36.p.rapidapi.com
    host: youtube-mp36.p.rapidapi.com
    apikey: 11d5a59a70msh928a6b51895e702p12ab87jsn7b4f24c628ba

imageprocessing:
  url: https://chatgpt-42.p.rapidapi.com/texttoimage3
  host: chatgpt-42.p.rapidapi.com
  apikey: f6f24ecde9mshd0292b17a6abc5fp11345fjsn6783b732b8cf




logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
